- name: Install Apache
  yum:
    name: httpd
    state: latest

- name: install php and php-mysql
  yum:
    name:
      - php
      - php-mysql

- name: Start service httpd, if not started
  service:
    name: httpd
    state: started