- name: Install firewalld
  yum:
    name: firewalld
    state: latest

- name: Start service firewalld, if not started
  service:
    name: firewalld
    state: started

- name: Add port for mysql
  firewalld:
    port: 3306/tcp
    permanent: yes
    state: enabled
    when: 'groupname' == 'database_servers'

- name: Add port for Apache
  firewalld:
    port: 80/tcp
    permanent: yes
    state: enabled
    when: 'groupname' == 'web_servers'

- name: Reload firewalld
  service:
    name: firewalld
    state: reloaded